require("dotenv").config();
const mongoose = require("mongoose");
const Saint = require("./models/saint");

mongoose.connect(process.env.MONGO_URI)
.then(() => console.log("MongoDB Connected ✅"))
.catch((err) => console.log(err));

const saintsData = [
    {
        name: "Sant Tukaram Maharaj",
        nameMarathi: "संत तुकाराम महाराज",
        birthYear: "1608",
        birthPlace: "Dehu, Pune",
        birthPlaceMarathi: "देहू, पुणे",
        godFollowed: "Vitthal (Lord Vishnu)",
        godFollowedMarathi: "विठ्ठल (भगवान विष्णू)",
        history: "Sant Tukaram was a 17th-century Hindu poet and sant of the Bhakti movement in Maharashtra. He was born in Dehu village near Pune. Despite facing many hardships including the death of his parents and first wife, he remained devoted to Lord Vitthal. His abhangas (devotional poetry) are considered masterpieces of Marathi literature. He emphasized devotion, equality, and criticized social evils. His teachings inspired millions and continue to guide spiritual seekers today.",
        historyMarathi: "संत तुकाराम १७व्या शतकातील महाराष्ट्रातील भक्ती चळवळीचे हिंदू कवी आणि संत होते. त्यांचा जन्म पुण्याजवळील देहू गावात झाला. आई-वडील आणि पहिल्या पत्नीच्या मृत्यूसह अनेक संकटांना तोंड देऊनही ते भगवान विठ्ठलाच्या भक्तीत रमले. त्यांचे अभंग मराठी साहित्याचे उत्कृष्ट नमुने मानले जातात. त्यांनी भक्ती, समानता यावर भर दिला आणि सामाजिक दुष्कृत्यांवर टीका केली. त्यांच्या शिकवणीने लाखो लोकांना प्रेरणा दिली आणि आजही आध्यात्मिक साधकांना मार्गदर्शन करत आहे.",
        literature: "Tukaram composed over 4,500 abhangas (devotional poems). His major works include Tukaram Gatha, a compilation of his abhangas. His poetry is simple yet profound, expressing deep devotion to Vitthal. He wrote about social justice, equality, and the path of bhakti. His compositions are sung in temples across Maharashtra even today.",
        literatureMarathi: "तुकारामांनी ४,५०० हून अधिक अभंग रचले. त्यांच्या प्रमुख कृतींमध्ये तुकाराम गाथा, त्यांच्या अभंगांचा संग्रह आहे. त्यांची कविता साधी पण गहन आहे, जी विठ्ठलाची खोल भक्ती व्यक्त करते. त्यांनी सामाजिक न्याय, समानता आणि भक्तीच्या मार्गाबद्दल लिहिले. त्यांच्या रचना आजही महाराष्ट्रभरातील मंदिरांमध्ये गायल्या जातात.",
        mantra: "विठ्ठल विठ्ठल विठोबा विठ्ठल",
        stotra: "पांडुरंग पांडुरंग विठ्ठल विठ्ठल\nमाझा विठ्ठल बोल विठ्ठल\nरुखमाई वल्लभ विठ्ठल\nपांडुरंग हरी विठ्ठल",
        image: "tukaram.jpg",
        region: "Paschim Maharashtra"
    },
    {
        name: "Sant Dnyaneshwar Maharaj",
        nameMarathi: "संत ज्ञानेश्वर महाराज",
        birthYear: "1275",
        birthPlace: "Apegaon, Paithan",
        birthPlaceMarathi: "आपेगाव, पैठण",
        godFollowed: "Lord Krishna",
        godFollowedMarathi: "भगवान कृष्ण",
        history: "Sant Dnyaneshwar, also known as Jnaneshwar, was a 13th-century Marathi saint, poet, philosopher and yogi. Born in Apegaon near Paithan, he was the second of four children. At the young age of 16, he wrote his masterpiece Dnyaneshwari, a commentary on the Bhagavad Gita in Marathi. He took samadhi at Alandi at the age of 21. He is considered one of the founders of the Varkari tradition and Marathi literature.",
        historyMarathi: "संत ज्ञानेश्वर, ज्यांना ज्ञानदेव म्हणूनही ओळखले जाते, १३व्या शतकातील मराठी संत, कवी, तत्त्वज्ञ आणि योगी होते. पैठणजवळील आपेगावात जन्मलेले, ते चार मुलांपैकी दुसरे होते. वयाच्या फक्त १६ व्या वर्षी त्यांनी भगवद्गीतेवर मराठीत भाष्य असलेली ज्ञानेश्वरी ही उत्कृष्ट कृती लिहिली. वयाच्या २१ व्या वर्षी त्यांनी आळंदी येथे समाधी घेतली. त्यांना वारकरी परंपरा आणि मराठी साहित्याच्या संस्थापकांपैकी एक मानले जाते.",
        literature: "His magnum opus is Dnyaneshwari (Bhavarth Deepika), a 9,000-verse commentary on Bhagavad Gita written in Marathi. He also composed Amrutanubhav, a treatise on Advaita Vedanta, and numerous abhangas. His works made spiritual knowledge accessible to common people in their own language.",
        literatureMarathi: "त्यांची महान कृती ज्ञानेश्वरी (भावार्थ दीपिका) आहे, जी भगवद्गीतेवर मराठीत लिहिलेली ९,००० ओव्यांची भाष्य आहे. त्यांनी अद्वैत वेदांतावरील ग्रंथ अमृतानुभव आणि असंख्य अभंग देखील रचले. त्यांच्या कृतींनी सामान्य लोकांना त्यांच्या स्वतःच्या भाषेत आध्यात्मिक ज्ञान सुलभ केले.",
        mantra: "ॐ नमो भगवते वासुदेवाय",
        stotra: "माऊली माऊली तूच माझा गोविंदा\nज्ञानदेवा तूच माझा पांडुरंगा",
        image: "dnyaneshwar.jpg",
        region: "Paschim Maharashtra"
    },
    {
        name: "Sant Eknath Maharaj",
        nameMarathi: "संत एकनाथ महाराज",
        birthYear: "1533",
        birthPlace: "Paithan, Aurangabad",
        birthPlaceMarathi: "पैठण, औरंगाबाद",
        godFollowed: "Lord Dattatreya & Vitthal",
        godFollowedMarathi: "भगवान दत्तात्रेय आणि विठ्ठल",
        history: "Sant Eknath was a 16th-century Marathi saint, scholar and religious poet. Born in Paithan, he was raised by his grandfather Bhanudas after his parents passed away early. He studied Vedas, Puranas and other scriptures. He revived the Varkari movement which had declined after Sant Dnyaneshwar. He was known for his compassion, treating everyone equally regardless of caste. He performed many social reforms and opposed caste discrimination.",
        historyMarathi: "संत एकनाथ १६व्या शतकातील मराठी संत, विद्वान आणि धार्मिक कवी होते. पैठणात जन्मलेले, त्यांचे पालनपोषण त्यांचे आजोबा भानुदास यांनी केले कारण त्यांचे आई-वडील लवकर वारले. त्यांनी वेद, पुराणे आणि इतर शास्त्रांचा अभ्यास केला. संत ज्ञानेश्वरांनंतर घसरलेल्या वारकरी चळवळीचे त्यांनी पुनरुज्जीवन केले. ते त्यांच्या करुणेसाठी ओळखले जात होते, जातीची पर्वा न करता सर्वांना समान वागवत होते. त्यांनी अनेक समाज सुधारणा केल्या आणि जातीय भेदभावाला विरोध केला.",
        literature: "Eknath wrote Eknathi Bhagavat, a Marathi commentary on the 11th chapter of Bhagavata Purana. He also wrote Bhavarth Ramayana and composed over 5,000 abhangas and bharuds. His works are known for their simplicity and spiritual depth.",
        literatureMarathi: "एकनाथांनी एकनाथी भागवत लिहिले, जे भागवत पुराणाच्या ११व्या स्कंधावर मराठीत भाष्य आहे. त्यांनी भावार्थ रामायण देखील लिहिले आणि ५,००० हून अधिक अभंग आणि भरूड रचले. त्यांची कृती साधेपणा आणि आध्यात्मिक खोलीसाठी ओळखली जातात.",
        mantra: "दिगंबरा दिगंबरा श्रीपाद वल्लभ दिगंबरा",
        stotra: "एकनाथ महाराज तुझी वाणी अमृतासारखी\nभक्तीचा मार्ग दाखवला जनासाठी",
        image: "eknath.jpg",
        region: "Marathwada"
    },
    {
        name: "Sant Namdev Maharaj",
        nameMarathi: "संत नामदेव महाराज",
        birthYear: "1270",
        birthPlace: "Narsi Bamani, Hingoli",
        birthPlaceMarathi: "नरसी बामणी, हिंगोली",
        godFollowed: "Vitthal",
        godFollowedMarathi: "विठ्ठल",
        history: "Sant Namdev was a 13th-14th century Marathi Varkari saint and poet. Born in a tailor family, he was a contemporary of Sant Dnyaneshwar. He traveled extensively across India spreading the message of bhakti. His abhangas are included in the Guru Granth Sahib, the holy book of Sikhs. He emphasized devotion over rituals and believed in the equality of all beings.",
        historyMarathi: "संत नामदेव १३व्या-१४व्या शतकातील मराठी वारकरी संत आणि कवी होते. शिंपी कुटुंबात जन्मलेले, ते संत ज्ञानेश्वरांचे समकालीन होते. त्यांनी भक्तीचा संदेश पसरवत संपूर्ण भारतात प्रवास केला. त्यांचे अभंग शीखांच्या पवित्र ग्रंथ गुरु ग्रंथ साहिबात समाविष्ट आहेत. त्यांनी विधींपेक्षा भक्तीवर भर दिला आणि सर्व प्राण्यांच्या समानतेवर विश्वास ठेवला.",
        literature: "Namdev composed over 2,500 abhangas in Marathi and also wrote in Hindi and Punjabi. His poetry expresses intense devotion to Vitthal. Around 60 of his hymns are included in Guru Granth Sahib. His works bridge different religious traditions.",
        literatureMarathi: "नामदेवांनी मराठीत २,५०० हून अधिक अभंग रचले आणि हिंदी व पंजाबीतही लिहिले. त्यांची कविता विठ्ठलाची तीव्र भक्ती व्यक्त करते. त्यांची सुमारे ६० स्तोत्रे गुरु ग्रंथ साहिबात समाविष्ट आहेत. त्यांची कृती विविध धार्मिक परंपरांना जोडतात.",
        mantra: "विठ्ठल विठ्ठल जय हरी विठ्ठल",
        stotra: "नामा म्हणे माझा पांडुरंगा\nविठ्ठल माझा सांगा",
        image: "namdev.jpg",
        region: "Marathwada"
    },
    {
        name: "Sant Ramdas Swami",
        nameMarathi: "संत रामदास स्वामी",
        birthYear: "1608",
        birthPlace: "Jamb, Jalna",
        birthPlaceMarathi: "जांब, जालना",
        godFollowed: "Lord Rama",
        godFollowedMarathi: "भगवान राम",
        history: "Sant Ramdas, also known as Samarth Ramdas, was a 17th-century Marathi saint and spiritual poet. He was the spiritual guru of Chhatrapati Shivaji Maharaj. Born as Narayan, he left home at 12 and spent 12 years in spiritual practice. He established temples of Hanuman across Maharashtra. He emphasized physical fitness along with spiritual development and inspired the Maratha warriors with his teachings.",
        historyMarathi: "संत रामदास, ज्यांना समर्थ रामदास म्हणूनही ओळखले जाते, १७व्या शतकातील मराठी संत आणि आध्यात्मिक कवी होते. ते छत्रपती शिवाजी महाराजांचे आध्यात्मिक गुरु होते. नारायण म्हणून जन्मलेले, त्यांनी १२ व्या वर्षी घर सोडले आणि १२ वर्षे आध्यात्मिक साधनेत घालवली. त्यांनी संपूर्ण महाराष्ट्रात हनुमानाची मंदिरे स्थापन केली. त्यांनी आध्यात्मिक विकासासोबत शारीरिक तंदुरुस्तीवर भर दिला आणि मराठा योद्ध्यांना त्यांच्या शिकवणीने प्रेरित केले.",
        literature: "His major works include Dasbodh, a spiritual text with 7,000 verses providing guidance on dharma and spiritual life. He also wrote Manache Shlok (51 verses on mind control), Karunashtakas, and numerous devotional songs. His writings combine spirituality with practical wisdom.",
        literatureMarathi: "त्यांच्या प्रमुख कृतींमध्ये दासबोध, धर्म आणि आध्यात्मिक जीवनावर मार्गदर्शन करणारा ७,००० श्लोकांचा आध्यात्मिक ग्रंथ आहे. त्यांनी मनाचे श्लोक (मन नियंत्रणावरील ५१ श्लोक), करुणाष्टके आणि असंख्य भक्तिगीते देखील लिहिली. त्यांचे लेखन अध्यात्म आणि व्यावहारिक शहाणपण एकत्र करते.",
        mantra: "श्रीराम जय राम जय जय राम",
        stotra: "मनाचे श्लोक सांगतो तुम्हाला\nमन हे साधावे सर्व साधनांचा मूळ",
        audio: "ramdas-mantra.mp3.m4a",
        image: "ramdas.jpg",
        region: "Marathwada"
    },
    {
        name: "Sant Janabai",
        nameMarathi: "संत जनाबाई",
        birthYear: "1263",
        birthPlace: "Gangakhed, Parbhani",
        birthPlaceMarathi: "गंगाखेड, परभणी",
        godFollowed: "Vitthal",
        godFollowedMarathi: "विठ्ठल",
        history: "Sant Janabai was a 13th-century Marathi saint and poet. She was a maidservant in the household of Sant Namdev's family. Despite her low social status, she became a renowned saint through her devotion. She saw God in her daily chores and expressed her devotion through abhangas. She is an inspiration for women's spirituality and showed that devotion transcends social barriers.",
        historyMarathi: "संत जनाबाई १३व्या शतकातील मराठी संत आणि कवयित्री होत्या. त्या संत नामदेवांच्या घरातील दासी होत्या. त्यांच्या निम्न सामाजिक स्थितीनंतरही, त्या त्यांच्या भक्तीमुळे प्रसिद्ध संत बनल्या. त्यांनी त्यांच्या दैनंदिन कामात देवाला पाहिले आणि अभंगांद्वारे त्यांची भक्ती व्यक्त केली. त्या स्त्रियांच्या अध्यात्मासाठी प्रेरणा आहेत आणि त्यांनी दाखवून दिले की भक्ती सामाजिक अडथळ्यांच्या पलीकडे जाते.",
        literature: "Janabai composed over 300 abhangas expressing her devotion to Vitthal. Her poetry describes her daily life, household work, and how she saw divinity in everything. Her abhangas are simple, heartfelt and reflect her deep spiritual experiences.",
        literatureMarathi: "जनाबाईंनी विठ्ठलाची भक्ती व्यक्त करणारे ३०० हून अधिक अभंग रचले. त्यांची कविता त्यांचे दैनंदिन जीवन, घरकाम आणि त्यांनी प्रत्येक गोष्टीत दिव्यत्व कसे पाहिले याचे वर्णन करते. त्यांचे अभंग साधे, मनापासून आणि त्यांच्या खोल आध्यात्मिक अनुभवांचे प्रतिबिंब आहेत.",
        mantra: "विठ्ठल विठ्ठल माझा पांडुरंग",
        stotra: "जनी म्हणे माझा विठ्ठल\nघरकाम करते विठ्ठल साथ देतो",
        image: "janabai.jpg",
        region: "Marathwada"
    },
    {
        name: "Sant Chokhamela",
        nameMarathi: "संत चोखामेळा",
        birthYear: "1300",
        birthPlace: "Mehuna, Buldhana",
        birthPlaceMarathi: "मेहुणा, बुलडाणा",
        godFollowed: "Vitthal",
        godFollowedMarathi: "विठ्ठल",
        history: "Sant Chokhamela was a 14th-century Marathi saint who belonged to the Mahar community, considered untouchable in those times. Despite facing severe caste discrimination, he remained devoted to Vitthal. He was not allowed to enter the Vitthal temple but would worship from outside. His devotion was so pure that he became a revered saint. He fought against caste discrimination through his poetry and life.",
        historyMarathi: "संत चोखामेळा १४व्या शतकातील मराठी संत होते जे महार समुदायाचे होते, त्या काळी अस्पृश्य मानले जात होते. तीव्र जातीय भेदभावाला तोंड देऊनही ते विठ्ठलाच्या भक्तीत रमले. त्यांना विठ्ठल मंदिरात प्रवेश करण्याची परवानगी नव्हती परंतु ते बाहेरून पूजा करत. त्यांची भक्ती इतकी शुद्ध होती की ते आदरणीय संत बनले. त्यांनी त्यांच्या कवितेद्वारे आणि जीवनाद्वारे जातीय भेदभावाविरुद्ध लढा दिला.",
        literature: "Chokhamela composed numerous abhangas expressing his devotion and pain of social discrimination. His poetry is powerful and emotional, highlighting the injustice of the caste system while maintaining unwavering faith in God. His works are a testament to spiritual equality.",
        literatureMarathi: "चोखामेळ्यांनी त्यांची भक्ती आणि सामाजिक भेदभावाची वेदना व्यक्त करणारे असंख्य अभंग रचले. त्यांची कविता शक्तिशाली आणि भावनिक आहे, जी जात व्यवस्थेच्या अन्यायाला उजाळा देते आणि देवावर अटूट विश्वास ठेवते. त्यांची कृती आध्यात्मिक समानतेचा पुरावा आहे.",
        mantra: "पांडुरंग विठ्ठल हरी विठ्ठल",
        stotra: "चोखा म्हणे माझा विठोबा\nजात पाहू नको प्रभू भक्ती पाहा",
        image: "chokhamela.jpg",
        region: "Vidarbha"
    },
    {
        name: "Sant Gora Kumbhar",
        nameMarathi: "संत गोरा कुंभार",
        birthYear: "1267",
        birthPlace: "Teredoki, Karnataka",
        birthPlaceMarathi: "तेरेडोकी, कर्नाटक",
        godFollowed: "Vitthal",
        godFollowedMarathi: "विठ्ठल",
        history: "Sant Gora Kumbhar was a 13th-century potter saint and a contemporary of Sant Namdev. He was a simple potter who saw God in his work. He would test his pots by tapping them, similarly he believed God tests humans. His devotion was so intense that according to legend, Vitthal himself appeared to him. He showed that any profession can be a path to God if done with devotion.",
        historyMarathi: "संत गोरा कुंभार १३व्या शतकातील कुंभार संत होते आणि संत नामदेवांचे समकालीन होते. ते एक साधे कुंभार होते ज्यांनी त्यांच्या कामात देवाला पाहिले. ते त्यांच्या भांड्यांची टोचून चाचणी घेत, त्याचप्रमाणे देव मानवांची परीक्षा घेतो असा त्यांचा विश्वास होता. त्यांची भक्ती इतकी तीव्र होती की पुराणानुसार विठ्ठल स्वतः त्यांना दर्शन दिले. त्यांनी दाखवून दिले की कोणताही व्यवसाय भक्तीने केला तर देवापर्यंत पोहोचण्याचा मार्ग असू शकतो.",
        literature: "Gora Kumbhar composed several abhangas comparing spiritual life to pottery. His poetry uses metaphors from his profession to explain spiritual concepts. His works emphasize that devotion and sincerity matter more than social status or learning.",
        literatureMarathi: "गोरा कुंभाराने आध्यात्मिक जीवनाची कुंभारकामाशी तुलना करणारे अनेक अभंग रचले. त्यांची कविता आध्यात्मिक संकल्पना स्पष्ट करण्यासाठी त्यांच्या व्यवसायातील रूपके वापरते. त्यांची कृती यावर भर देतात की भक्ती आणि प्रामाणिकपणा सामाजिक स्थिती किंवा शिक्षणापेक्षा अधिक महत्त्वाचे आहे.",
        mantra: "विठ्ठल विठ्ठल पांडुरंग हरी",
        stotra: "गोरा म्हणे माझा पांडुरंग\nमाती सारखे घडव मला विठोबा",
        image: "gorakumbhar.jpg",
        region: "Paschim Maharashtra"
    },
    {
        name: "Sant Muktabai",
        nameMarathi: "संत मुक्ताबाई",
        birthYear: "1279",
        birthPlace: "Apegaon, Paithan",
        birthPlaceMarathi: "आपेगाव, पैठण",
        godFollowed: "Lord Vitthal",
        godFollowedMarathi: "भगवान विठ्ठल",
        history: "Sant Muktabai was the younger sister of Sant Dnyaneshwar and a 13th-century Marathi saint and poet. She was one of the four siblings who were all saints. Despite being a woman in medieval times, she composed powerful abhangas and spiritual poetry. She was known for her wisdom and devotion. Her works reflect deep spiritual understanding and devotion to Vitthal. She is considered one of the earliest women saints in the Varkari tradition.",
        historyMarathi: "संत मुक्ताबाई संत ज्ञानेश्वरांची धाकटी बहीण आणि १३व्या शतकातील मराठी संत आणि कवयित्री होत्या. ती चार भावंडांपैकी एक होती जे सर्व संत होते. मध्ययुगीन काळात स्त्री असूनही तिने शक्तिशाली अभंग आणि आध्यात्मिक कविता रचल्या. ती तिच्या शहाणपणासाठी आणि भक्तीसाठी ओळखली जात होती. तिची कृती खोल आध्यात्मिक समज आणि विठ्ठलाची भक्ती प्रतिबिंबित करतात. तिला वारकरी परंपरेतील सर्वात प्राचीन महिला संतांपैकी एक मानले जाते.",
        literature: "Muktabai composed around 50 abhangas that are known for their spiritual depth and devotional fervor. Her poetry expresses her experiences of divine love and spiritual awakening. She wrote about the nature of God, devotion, and the path to liberation. Her works are included in various compilations of Marathi devotional literature.",
        literatureMarathi: "मुक्ताबाईंनी सुमारे ५० अभंग रचले जे त्यांच्या आध्यात्मिक खोली आणि भक्तीच्या उत्कटतेसाठी ओळखले जातात. तिची कविता दैवी प्रेम आणि आध्यात्मिक जागृतीचे तिचे अनुभव व्यक्त करते. तिने देवाचे स्वरूप, भक्ती आणि मुक्तीचा मार्ग याबद्दल लिहिले. तिची कृती मराठी भक्ती साहित्याच्या विविध संग्रहांमध्ये समाविष्ट आहेत.",
        mantra: "विठ्ठल विठ्ठल पांडुरंगा",
        stotra: "मुक्ता म्हणे माझा पांडुरंगा\nभक्तीने साधावे चरण तुझे",
        image: "muktabai.jpg",
        region: "Paschim Maharashtra"
    },
    {
        name: "Sant Savata Mali",
        nameMarathi: "संत सावता माळी",
        birthYear: "1300",
        birthPlace: "Akluj, Solapur",
        birthPlaceMarathi: "आकलूज, सोलापूर",
        godFollowed: "Lord Vitthal",
        godFollowedMarathi: "भगवान विठ्ठल",
        history: "Sant Savata Mali was a 14th-century Marathi saint who belonged to the gardener (Mali) community. He was a contemporary of Sant Namdev and Sant Chokhamela. Despite his humble profession as a gardener, he became a revered saint through his devotion to Vitthal. He would offer flowers to Vitthal with pure devotion. His life exemplifies that devotion knows no social boundaries and that God accepts offerings made with love and sincerity.",
        historyMarathi: "संत सावता माळी १४व्या शतकातील मराठी संत होते जे माळी समुदायाचे होते. ते संत नामदेव आणि संत चोखामेळा यांचे समकालीन होते. माळी म्हणून त्यांचा नम्र व्यवसाय असूनही ते विठ्ठलाच्या भक्तीमुळे आदरणीय संत बनले. ते शुद्ध भक्तीने विठ्ठलाला फुले अर्पण करत. त्यांचे जीवन हे दाखवून देते की भक्ती कोणत्याही सामाजिक सीमा ओळखत नाही आणि देव प्रेम आणि प्रामाणिकपणाने केलेले अर्पण स्वीकारतो.",
        literature: "Savata Mali composed several abhangas expressing his devotion to Vitthal. His poetry often uses imagery from his profession as a gardener, comparing spiritual cultivation to tending a garden. His works emphasize the importance of pure devotion over social status. His abhangas are simple yet profound, reflecting his humble nature and deep faith.",
        literatureMarathi: "सावता माळीने विठ्ठलाची भक्ती व्यक्त करणारे अनेक अभंग रचले. त्यांची कविता अनेकदा माळी म्हणून त्यांच्या व्यवसायातील प्रतिमा वापरते, आध्यात्मिक लागवडीची बागेची काळजी घेण्याशी तुलना करते. त्यांची कृती सामाजिक स्थितीपेक्षा शुद्ध भक्तीच्या महत्त्वावर भर देतात. त्यांचे अभंग साधे पण गहन आहेत, जे त्यांचे नम्र स्वभाव आणि खोल विश्वास प्रतिबिंबित करतात.",
        mantra: "विठ्ठल विठ्ठल माझा पांडुरंग",
        stotra: "सावता म्हणे माझा विठोबा\nफुलांचे अर्पण घे प्रभू",
        image: "savatamali.jpg",
        region: "Paschim Maharashtra"
    },
    {
        name: "Sant Sena Nhavi",
        nameMarathi: "संत सेना न्हावी",
        birthYear: "1300",
        birthPlace: "Pathri, Parbhani",
        birthPlaceMarathi: "पाथरी, परभणी",
        godFollowed: "Lord Vitthal",
        godFollowedMarathi: "भगवान विठ्ठल",
        history: "Sant Sena Nhavi was a 14th-century Marathi saint who worked as a barber (Nhavi). He was a contemporary of Sant Namdev and part of the Varkari tradition. Despite his profession being considered lowly in the caste hierarchy, he became a respected saint through his devotion. He would serve people while chanting the name of Vitthal. His life demonstrates that spiritual greatness is not determined by birth or profession but by devotion and service to God.",
        historyMarathi: "संत सेना न्हावी १४व्या शतकातील मराठी संत होते जे न्हावी (नाई) म्हणून काम करत होते. ते संत नामदेवांचे समकालीन होते आणि वारकरी परंपरेचा भाग होते. जातीच्या पदानुक्रमात त्यांचा व्यवसाय निम्न मानला जात असूनही ते त्यांच्या भक्तीमुळे आदरणीय संत बनले. ते विठ्ठलाचे नाव घेत लोकांची सेवा करत. त्यांचे जीवन हे दाखवून देते की आध्यात्मिक महानता जन्म किंवा व्यवसायाने ठरत नाही तर भक्ती आणि देवाची सेवा यावरून ठरते.",
        literature: "Sena Nhavi composed abhangas that reflect his devotion to Vitthal and his philosophy of serving God through serving people. His poetry emphasizes the importance of humility, service, and devotion. He used simple language that common people could understand. His works show that every profession can be a means of worship if done with devotion.",
        literatureMarathi: "सेना न्हावीने विठ्ठलाची भक्ती आणि लोकांची सेवा करून देवाची सेवा करण्याचे त्यांचे तत्त्वज्ञान प्रतिबिंबित करणारे अभंग रचले. त्यांची कविता नम्रता, सेवा आणि भक्तीच्या महत्त्वावर भर देते. त्यांनी सामान्य लोकांना समजेल अशी साधी भाषा वापरली. त्यांची कृती दाखवतात की प्रत्येक व्यवसाय भक्तीने केला तर उपासनेचे साधन असू शकतो.",
        mantra: "विठ्ठल विठ्ठल जय हरी विठ्ठल",
        stotra: "सेना म्हणे माझा पांडुरंगा\nसेवा करतो तुझ्या नामाने",
        image: "senanhavi.jpg",
        region: "Marathwada"
    },
    {
        name: "Sant Rohidas",
        nameMarathi: "संत रोहिदास",
        birthYear: "1450",
        birthPlace: "Varanasi (Associated with Maharashtra)",
        birthPlaceMarathi: "वाराणसी (महाराष्ट्राशी संबंधित)",
        godFollowed: "Lord Rama",
        godFollowedMarathi: "भगवान राम",
        history: "Sant Rohidas (also known as Ravidas) was a 15th-century saint and poet who belonged to the cobbler community. Though born in Varanasi, his teachings and poetry had significant influence in Maharashtra. He was a contemporary of Kabir and his verses are included in the Guru Granth Sahib. He preached equality and opposed the caste system. His philosophy emphasized that God is accessible to all regardless of birth or social status.",
        historyMarathi: "संत रोहिदास (रविदास म्हणूनही ओळखले जाते) १५व्या शतकातील संत आणि कवी होते जे चर्मकार समुदायाचे होते. वाराणसीत जन्मलेले असले तरी त्यांच्या शिकवणी आणि कवितेचा महाराष्ट्रात महत्त्वपूर्ण प्रभाव होता. ते कबीरांचे समकालीन होते आणि त्यांचे श्लोक गुरु ग्रंथ साहिबात समाविष्ट आहेत. त्यांनी समानतेचा उपदेश केला आणि जात व्यवस्थेला विरोध केला. त्यांचे तत्त्वज्ञान यावर भर देते की जन्म किंवा सामाजिक स्थितीची पर्वा न करता देव सर्वांसाठी सुलभ आहे.",
        literature: "Rohidas composed numerous devotional poems and bhajans. His poetry is characterized by its simplicity and profound spiritual message. He wrote about the oneness of God, the futility of caste distinctions, and the importance of devotion. His works are sung and revered across India. Around 40 of his hymns are included in the Guru Granth Sahib.",
        literatureMarathi: "रोहिदासांनी असंख्य भक्तिगीते आणि भजने रचली. त्यांची कविता साधेपणा आणि गहन आध्यात्मिक संदेशाने वैशिष्ट्यीकृत आहे. त्यांनी देवाचे एकत्व, जातीय भेदांची निरर्थकता आणि भक्तीचे महत्त्व याबद्दल लिहिले. त्यांची कृती संपूर्ण भारतात गायली जातात आणि त्यांचा आदर केला जातो. त्यांची सुमारे ४० स्तोत्रे गुरु ग्रंथ साहिबात समाविष्ट आहेत.",
        mantra: "राम नाम सत्य है",
        stotra: "रोहिदास म्हणे प्रभू तुझे नाम\nसर्वांना मुक्ती देणारे",
        image: "rohidas.jpg",
        region: "Vidarbha"
    },
    {
        name: "Sai Baba of Shirdi",
        nameMarathi: "शिर्डीचे साईबाबा",
        birthYear: "1838",
        birthPlace: "Pathri, Parbhani",
        birthPlaceMarathi: "पाथरी, परभणी",
        godFollowed: "Universal (Hindu-Muslim Unity)",
        godFollowedMarathi: "सार्वभौमिक (हिंदू-मुस्लिम एकता)",
        history: "Sai Baba of Shirdi was a spiritual master who lived in Shirdi, Maharashtra. He is revered by both Hindu and Muslim devotees. His teachings combined elements of Hinduism and Islam, emphasizing the importance of self-realization, charity, contentment, inner peace, and devotion to God. He performed many miracles and helped countless people. His philosophy of 'Sabka Malik Ek' (One God governs all) promoted religious harmony. He lived a simple life in a mosque called Dwarkamai and distributed all donations to the poor.",
        historyMarathi: "शिर्डीचे साईबाबा हे महाराष्ट्रातील शिर्डी येथे राहणारे आध्यात्मिक गुरु होते. त्यांना हिंदू आणि मुस्लिम दोन्ही भक्त मानतात. त्यांच्या शिकवणीत हिंदू आणि इस्लाम धर्माचे घटक एकत्र होते, जे आत्म-साक्षात्कार, दान, समाधान, आंतरिक शांती आणि देवाची भक्ती यावर भर देत होते. त्यांनी अनेक चमत्कार केले आणि असंख्य लोकांना मदत केली. 'सबका मालिक एक' हे त्यांचे तत्त्वज्ञान धार्मिक सौहार्द वाढवते. ते द्वारकामाई नावाच्या मशिदीत साधे जीवन जगत होते आणि सर्व दान गरीबांना वाटत होते.",
        literature: "Sai Baba did not write any books himself, but his teachings were recorded by his disciples. The most famous compilation is 'Shri Sai Satcharitra' written by Govind Raghunath Dabholkar (Hemadpant). This book contains his life story, teachings, and miracles. His sayings emphasized faith (Shraddha) and patience (Saburi). His teachings are simple yet profound, accessible to people of all backgrounds.",
        literatureMarathi: "साईबाबांनी स्वतः कोणतेही पुस्तक लिहिले नाही, परंतु त्यांच्या शिकवणी त्यांच्या शिष्यांनी नोंदवल्या. सर्वात प्रसिद्ध संकलन म्हणजे गोविंद रघुनाथ दाभोलकर (हेमाडपंत) यांनी लिहिलेले 'श्री साई सच्चरित्र'. या पुस्तकात त्यांची जीवनकथा, शिकवणी आणि चमत्कार आहेत. त्यांच्या उक्तींमध्ये श्रद्धा आणि सबुरी यावर भर होता. त्यांच्या शिकवणी साध्या पण गहन आहेत, सर्व पार्श्वभूमीच्या लोकांसाठी सुलभ आहेत.",
        mantra: "ॐ साईं श्री साईं जय जय साईं",
        stotra: "श्रद्धा सबुरी साईं\nसबका मालिक एक",
        image: "saibaba.jpg",
        region: "Marathwada"
    },
    {
        name: "Gajanan Maharaj of Shegaon",
        nameMarathi: "शेगावचे गजानन महाराज",
        birthYear: "1856",
        birthPlace: "Unknown (Appeared in Shegaon)",
        birthPlaceMarathi: "अज्ञात (शेगावात प्रकट झाले)",
        godFollowed: "Lord Dattatreya",
        godFollowedMarathi: "भगवान दत्तात्रेय",
        history: "Gajanan Maharaj was a saint who appeared in Shegaon, Maharashtra in 1878. His origins are unknown, and he was first seen eating leftover food from a garbage heap. Despite his unusual behavior, people recognized his spiritual powers. He performed many miracles and helped devotees overcome their problems. He established an ashram in Shegaon which continues to serve millions of devotees. He took samadhi in 1910. He is considered an incarnation of Lord Dattatreya.",
        historyMarathi: "गजानन महाराज हे १८७८ मध्ये महाराष्ट्रातील शेगाव येथे प्रकट झालेले संत होते. त्यांची उत्पत्ती अज्ञात आहे आणि त्यांना प्रथम कचऱ्याच्या ढिगाऱ्यातून उरलेले अन्न खाताना पाहिले गेले. त्यांचे असामान्य वर्तन असूनही लोकांनी त्यांची आध्यात्मिक शक्ती ओळखली. त्यांनी अनेक चमत्कार केले आणि भक्तांना त्यांच्या समस्यांवर मात करण्यास मदत केली. त्यांनी शेगावात एक आश्रम स्थापन केला जो लाखो भक्तांची सेवा करत आहे. १९१० मध्ये त्यांनी समाधी घेतली. त्यांना भगवान दत्तात्रेयाचा अवतार मानले जाते.",
        literature: "The life and teachings of Gajanan Maharaj are documented in 'Shri Gajanan Vijay', a Marathi book written by Das Ganu Maharaj (Damodar Savalaram Gavankar). This book contains 21 chapters describing his life, miracles, and spiritual teachings. It is written in the form of poetry (ovi meter) and is considered a sacred text by his devotees.",
        literatureMarathi: "गजानन महाराजांचे जीवन आणि शिकवणी 'श्री गजानन विजय' या मराठी पुस्तकात नोंदवल्या आहेत, जे दासगणू महाराज (दामोदर सावळाराम गवणकर) यांनी लिहिले आहे. या पुस्तकात त्यांचे जीवन, चमत्कार आणि आध्यात्मिक शिकवणी वर्णन करणारे २१ अध्याय आहेत. हे ओवी छंदात लिहिलेले आहे आणि त्यांच्या भक्तांद्वारे पवित्र ग्रंथ मानले जाते.",
        mantra: "गणपती बाप्पा मोरया",
        stotra: "गजानन गजानन श्री गजानन महाराज\nदत्त दिगंबर दत्त",
        image: "gajananmaharaj.jpg",
        region: "Vidarbha"
    },
    {
        name: "Swami Samarth of Akkalkot",
        nameMarathi: "अक्कलकोटचे स्वामी समर्थ",
        birthYear: "Unknown",
        birthPlace: "Unknown (Appeared in Akkalkot)",
        birthPlaceMarathi: "अज्ञात (अक्कलकोटात प्रकट झाले)",
        godFollowed: "Lord Dattatreya",
        godFollowedMarathi: "भगवान दत्तात्रेय",
        history: "Swami Samarth of Akkalkot was a spiritual master who lived in Akkalkot, Maharashtra in the 19th century. He is believed to be an incarnation of Lord Dattatreya. His origins are mysterious, and he appeared in Akkalkot around 1856. He performed numerous miracles and guided many disciples. He lived for about 22 years in Akkalkot and took samadhi in 1878. Many believe he was the same soul as Narasimha Saraswati. His teachings emphasized devotion, meditation, and service to humanity.",
        historyMarathi: "अक्कलकोटचे स्वामी समर्थ हे १९व्या शतकात महाराष्ट्रातील अक्कलकोट येथे राहणारे आध्यात्मिक गुरु होते. त्यांना भगवान दत्तात्रेयाचा अवतार मानले जाते. त्यांची उत्पत्ती गूढ आहे आणि ते १८५६ च्या सुमारास अक्कलकोटात प्रकट झाले. त्यांनी असंख्य चमत्कार केले आणि अनेक शिष्यांना मार्गदर्शन केले. ते अक्कलकोटात सुमारे २२ वर्षे राहिले आणि १८७८ मध्ये समाधी घेतली. अनेकांचा असा विश्वास आहे की ते नरसिंह सरस्वती सारखेच आत्मा होते. त्यांच्या शिकवणीत भक्ती, ध्यान आणि मानवतेची सेवा यावर भर होता.",
        literature: "The life and teachings of Swami Samarth are documented in various books including 'Shri Gurucharitra' and biographies written by his disciples. His teachings were mostly oral, emphasizing practical spirituality. Stories of his miracles and interactions with devotees have been compiled by various authors. His philosophy focused on self-realization and devotion to God.",
        literatureMarathi: "स्वामी समर्थांचे जीवन आणि शिकवणी 'श्री गुरुचरित्र' आणि त्यांच्या शिष्यांनी लिहिलेल्या चरित्रांसह विविध पुस्तकांमध्ये नोंदवल्या आहेत. त्यांच्या शिकवणी मुख्यतः मौखिक होत्या, व्यावहारिक अध्यात्मावर भर देत होत्या. त्यांच्या चमत्कारांच्या आणि भक्तांशी संवादाच्या कथा विविध लेखकांनी संकलित केल्या आहेत. त्यांचे तत्त्वज्ञान आत्म-साक्षात्कार आणि देवाची भक्ती यावर केंद्रित होते.",
        mantra: "दत्त दिगंबर दिगंबर दत्त",
        stotra: "दिगंबरा दिगंबरा श्रीपाद वल्लभ दिगंबरा\nस्वामी समर्थ महाराज की जय",
        image: "swamiSamarth.jpg",
        region: "Paschim Maharashtra"
    },
    {
        name: "Tajuddin Baba of Nagpur",
        nameMarathi: "नागपूरचे ताजुद्दीन बाबा",
        birthYear: "1861",
        birthPlace: "Kamthi, Nagpur",
        birthPlaceMarathi: "कामठी, नागपूर",
        godFollowed: "Universal (Sufi Saint)",
        godFollowedMarathi: "सार्वभौमिक (सूफी संत)",
        history: "Tajuddin Baba was a Sufi saint who lived in Nagpur, Maharashtra. He was a contemporary of Sai Baba of Shirdi and they met several times. He lived a life of complete renunciation and often appeared to be mad, but his spiritual powers were recognized by many. He spent 16 years in a mental asylum where he continued to help people spiritually. He performed many miracles and helped people regardless of their religion. He took samadhi in 1925. His dargah in Nagpur is visited by people of all faiths.",
        historyMarathi: "ताजुद्दीन बाबा हे महाराष्ट्रातील नागपूर येथे राहणारे सूफी संत होते. ते शिर्डीच्या साईबाबांचे समकालीन होते आणि त्यांची अनेक वेळा भेट झाली. त्यांनी संपूर्ण त्यागाचे जीवन जगले आणि अनेकदा वेडे दिसत होते, परंतु त्यांची आध्यात्मिक शक्ती अनेकांनी ओळखली. त्यांनी मानसिक रुग्णालयात १६ वर्षे घालवली जिथे त्यांनी लोकांना आध्यात्मिकरित्या मदत करणे सुरू ठेवले. त्यांनी अनेक चमत्कार केले आणि त्यांच्या धर्माची पर्वा न करता लोकांना मदत केली. १९२५ मध्ये त्यांनी समाधी घेतली. नागपूरमधील त्यांच्या दर्गाला सर्व धर्मांचे लोक भेट देतात.",
        literature: "The life of Tajuddin Baba is documented in various biographies written by his devotees. His teachings were mostly through actions rather than words. Stories of his miracles and spiritual guidance have been compiled in books. His life exemplifies the Sufi tradition of divine madness and complete surrender to God.",
        literatureMarathi: "ताजुद्दीन बाबांचे जीवन त्यांच्या भक्तांनी लिहिलेल्या विविध चरित्रांमध्ये नोंदवले आहे. त्यांच्या शिकवणी शब्दांपेक्षा कृतींद्वारे होत्या. त्यांच्या चमत्कारांच्या आणि आध्यात्मिक मार्गदर्शनाच्या कथा पुस्तकांमध्ये संकलित केल्या आहेत. त्यांचे जीवन दैवी वेडेपणा आणि देवाला संपूर्ण समर्पण या सूफी परंपरेचे उदाहरण आहे.",
        mantra: "अल्लाह हू अल्लाह",
        stotra: "ताजुद्दीन बाबा की जय\nसबका मालिक एक",
        image: "tajuddinbaba.jpg",
        region: "Vidarbha"
    },
    {
        name: "Gondavalekar Maharaj",
        nameMarathi: "गोंदवलेकर महाराज",
        birthYear: "1845",
        birthPlace: "Gondavale, Satara",
        birthPlaceMarathi: "गोंदवले, सातारा",
        godFollowed: "Lord Rama",
        godFollowedMarathi: "भगवान राम",
        history: "Brahmachaitanya Gondavalekar Maharaj was a 19th-century saint from Gondavale, Maharashtra. He was a great devotee of Lord Rama and emphasized the chanting of Ram Naam. He established an ashram in Gondavale which became a center for spiritual learning. He taught that continuous chanting of God's name is the easiest path to liberation. He initiated thousands of disciples into Ram Naam. He took samadhi in 1913. His teachings continue through his ashram which serves devotees from all over India.",
        historyMarathi: "ब्रह्मचैतन्य गोंदवलेकर महाराज हे १९व्या शतकातील महाराष्ट्रातील गोंदवले येथील संत होते. ते भगवान रामाचे महान भक्त होते आणि राम नामाच्या जपावर भर देत होते. त्यांनी गोंदवले येथे एक आश्रम स्थापन केला जो आध्यात्मिक शिक्षणाचे केंद्र बनला. त्यांनी शिकवले की देवाच्या नावाचा सतत जप हा मुक्तीचा सर्वात सोपा मार्ग आहे. त्यांनी हजारो शिष्यांना राम नामात दीक्षा दिली. १९१३ मध्ये त्यांनी समाधी घेतली. त्यांच्या शिकवणी त्यांच्या आश्रमाद्वारे चालू आहेत जो संपूर्ण भारतातील भक्तांची सेवा करतो.",
        literature: "Gondavalekar Maharaj's teachings are compiled in various books and discourses. His main teaching was the importance of Ram Naam japa. He wrote commentaries on spiritual texts and gave numerous discourses on devotion and spirituality. His ashram continues to publish his teachings and maintain his spiritual legacy.",
        literatureMarathi: "गोंदवलेकर महाराजांच्या शिकवणी विविध पुस्तके आणि प्रवचनांमध्ये संकलित आहेत. त्यांची मुख्य शिकवण राम नाम जपाचे महत्त्व होते. त्यांनी आध्यात्मिक ग्रंथांवर भाष्ये लिहिली आणि भक्ती आणि अध्यात्मावर असंख्य प्रवचने दिली. त्यांचा आश्रम त्यांच्या शिकवणी प्रकाशित करत आहे आणि त्यांचा आध्यात्मिक वारसा टिकवून ठेवत आहे.",
        mantra: "श्रीराम जय राम जय जय राम",
        stotra: "राम नाम सत्य है\nराम नाम तारक है",
        image: "gondavalekar.jpg",
        region: "Paschim Maharashtra"
    },
    {
        name: "Sant Bhagwan Baba",
        nameMarathi: "संत भगवान बाबा",
        birthYear: "1850",
        birthPlace: "Dhule, Maharashtra",
        birthPlaceMarathi: "धुळे, महाराष्ट्र",
        godFollowed: "Universal Divine",
        godFollowedMarathi: "सार्वभौमिक दैवी",
        history: "Sant Bhagwan Baba was a spiritual master from Maharashtra who lived in the 19th-20th century. He was known for his simple living and profound spiritual wisdom. He emphasized the unity of all religions and taught that God can be realized through any path followed with sincerity. He helped many people overcome their difficulties through his spiritual guidance. He performed miracles but always attributed them to God's grace. His teachings focused on love, compassion, and service to humanity.",
        historyMarathi: "संत भगवान बाबा हे १९व्या-२०व्या शतकात राहणारे महाराष्ट्रातील आध्यात्मिक गुरु होते. ते त्यांच्या साध्या जीवनासाठी आणि गहन आध्यात्मिक शहाणपणासाठी ओळखले जात होते. त्यांनी सर्व धर्मांच्या एकतेवर भर दिला आणि शिकवले की प्रामाणिकपणे अनुसरण केलेल्या कोणत्याही मार्गाने देवाची प्राप्ती होऊ शकते. त्यांनी त्यांच्या आध्यात्मिक मार्गदर्शनाद्वारे अनेक लोकांना त्यांच्या अडचणींवर मात करण्यास मदत केली. त्यांनी चमत्कार केले परंतु नेहमी ते देवाच्या कृपेला श्रेय दिले. त्यांच्या शिकवणीत प्रेम, करुणा आणि मानवतेची सेवा यावर भर होता.",
        literature: "Sant Bhagwan Baba's teachings were mostly oral and have been preserved through the memories of his disciples. His simple yet profound teachings emphasized practical spirituality and devotion. Stories of his life and miracles have been compiled by his followers. His philosophy stressed the importance of inner transformation and selfless service.",
        literatureMarathi: "संत भगवान बाबांच्या शिकवणी मुख्यतः मौखिक होत्या आणि त्यांच्या शिष्यांच्या आठवणींद्वारे जतन केल्या गेल्या आहेत. त्यांच्या साध्या पण गहन शिकवणीत व्यावहारिक अध्यात्म आणि भक्ती यावर भर होता. त्यांच्या जीवनाच्या आणि चमत्कारांच्या कथा त्यांच्या अनुयायांनी संकलित केल्या आहेत. त्यांच्या तत्त्वज्ञानात आंतरिक परिवर्तन आणि निःस्वार्थ सेवा यांच्या महत्त्वावर भर होता.",
        mantra: "ॐ नमः शिवाय",
        stotra: "भगवान बाबा की जय\nसर्व धर्म समभाव",
        image: "bhagwanbaba.jpg",
        region: "Khandesh"
    }
];

async function seedDatabase() {
    try {
        await Saint.deleteMany({});
        console.log("Cleared existing data");
        
        await Saint.insertMany(saintsData);
        console.log("✅ Successfully added all Maharashtra saints with Marathi translations!");
        
        mongoose.connection.close();
    } catch (error) {
        console.error("Error seeding database:", error);
    }
}

seedDatabase();
